USE customer_behaviour;
SELECT * FROM CustomerData;
--Q1. What is the total revenue generated by male vs. female customers?
 
SELECT 
    Gender,
    SUM([Purchase Amount (USD)]) AS total_revenue_usd
FROM dbo.CustomerData
GROUP BY Gender;
--Q2. Which customers used a discount but still spent more than the average purchase amount? 
USE customer_behaviour;

SELECT 
    [Customer ID],
    [Purchase Amount (USD)]
FROM dbo.CustomerData
WHERE 
    [Discount Applied] = 'Yes'
    AND [Purchase Amount (USD)] >= (
        SELECT AVG([Purchase Amount (USD)])
        FROM dbo.CustomerData
    );
-- Q3. Which are the top 5 products with the highest average review rating?
USE customer_behaviour;

SELECT TOP 5
    [Item Purchased],
    ROUND(AVG(CAST([Review Rating] AS FLOAT)), 2) AS [Average Product Rating]
FROM dbo.CustomerData
GROUP BY [Item Purchased]
ORDER BY AVG(CAST([Review Rating] AS FLOAT)) DESC;

USE customer_behaviour;
--Q4. Compare the average Purchase Amounts between Standard and Express Shipping.
SELECT 
    [Shipping Type],
    ROUND(AVG(CAST([Purchase Amount (USD)] AS FLOAT)), 2) AS Avg_Purchase
FROM dbo.CustomerData
WHERE [Shipping Type] IN ('Standard','Express')
GROUP BY [Shipping Type];
--Q5. Do subscribed customers spend more? Compare average spend and total revenue 
--between subscribers and non-subscribers.
USE customer_behaviour;

SELECT 
    [Subscription Status],
    COUNT([Customer ID]) AS total_customers,
    ROUND(AVG(CAST([Purchase Amount (USD)] AS FLOAT)), 2) AS avg_spend,
    ROUND(SUM(CAST([Purchase Amount (USD)] AS FLOAT)), 2) AS total_revenue
FROM dbo.CustomerData
GROUP BY [Subscription Status]
ORDER BY total_revenue DESC, avg_spend DESC;

--Q6. Which 5 products have the highest percentage of purchases with discounts applied?
USE customer_behaviour;

SELECT TOP 5
    [Item Purchased],
    ROUND(
        100.0 * 
        SUM(CASE WHEN [Discount Applied] = 'Yes' THEN 1 ELSE 0 END) 
        / COUNT(*),
        2
    ) AS discount_rate
FROM dbo.CustomerData
GROUP BY [Item Purchased]
ORDER BY discount_rate DESC;


--Q7. Segment customers into New, Returning, and Loyal based on their total 
-- number of previous purchases, and show the count of each segment. 

USE customer_behaviour;

WITH customer_type AS (
    SELECT 
        [Customer ID],
        [Previous Purchases],
        CASE 
            WHEN [Previous Purchases] = 1 THEN 'New'
            WHEN [Previous Purchases] BETWEEN 2 AND 10 THEN 'Returning'
            ELSE 'Loyal'
        END AS customer_segment
    FROM dbo.CustomerData
)
SELECT 
    customer_segment,
    COUNT(*) AS [Number of Customers]
FROM customer_type
GROUP BY customer_segment;

--Q8. What are the top 3 most purchased products within each category? 

USE customer_behaviour;

WITH item_counts AS (
    SELECT 
        [Category],
        [Item Purchased],
        COUNT([Customer ID]) AS total_orders,
        ROW_NUMBER() OVER (
            PARTITION BY [Category]
            ORDER BY COUNT([Customer ID]) DESC
        ) AS item_rank
    FROM dbo.CustomerData
    GROUP BY [Category], [Item Purchased]
)
SELECT 
    item_rank,
    [Category],
    [Item Purchased],
    total_orders
FROM item_counts
WHERE item_rank <= 3;
--Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
 USE customer_behaviour;

SELECT 
    [Subscription Status],
    COUNT([Customer ID]) AS repeat_buyers
FROM dbo.CustomerData
WHERE [Previous Purchases] > 5
GROUP BY [Subscription Status];

--Q10. What is the revenue contribution of each age group? 
USE customer_behaviour;

SELECT 
    [Age],
    SUM(CAST([Purchase Amount (USD)] AS FLOAT)) AS total_revenue
FROM dbo.CustomerData
GROUP BY [Age]
ORDER BY total_revenue DESC;






